#!/bin/bash
#PBS -l  nodes=1:ppn=8
#PBS -l  walltime=2:00:00
##PBS -l  pmem=5gb
#PBS -N  AICON
#PBS -q  batch
#PBS -j  eo

module load Compiler/GCC/5.3.1 MPI/impi/2017.0.4 MKL/2017.4.239
cd ${PBS_O_WORKDIR}
#NPROCS=`wc -l < $PBS_NODEFILE`
#mpirun -hostfile $PBS_NODEFILE -np $NPROCS --bind-to core vasp_std
#mpirun -np ${PBS_NP} $HOME/bin/vasp_ncl > log
python aiconforele.py
